### ISSUE TITLE
A test flaking

### ISSUE THREAD

**Issue by Powersource** [staltz/ssb-search2#3]
After this PR it's passing locally but failing on one test in CI https://github.com/ssbc/ssb-search2/pull/2 (not sure what was the status before the PR, it couldn't install for me)

**Comment by Powersource** [comment]
oh gdi now got it to fail locally too. i guess some race condition/flake. hopefully not a problem in real life scenarios

```
exact chain-of-words

    ✔ no error

    ✖ four posts
    -------------
      operator: equal
      expected: 4
      actual:   2
      at: <anonymous> (/home/me/prj/ssb/ssb-search2/test/index.js:72:9)
      stack: |-
  Error: four posts
  at Test.assert [as _assert] (/home/me/prj/ssb/ssb-search2/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:310:54)
  at Test.bound [as _assert] (/home/me/prj/ssb/ssb-search2/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:91:32)
  at Test.strictEqual (/home/me/prj/ssb/ssb-search2/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:474:10)
  at Test.bound [as equals] (/home/me/prj/ssb/ssb-search2/node_modules/.pnpm/tape@5.2.0/node_modules/tape/lib/test.js:91:32)
  at /home/me/prj/ssb/ssb-search2/test/index.js:72:9
  at /home/me/prj/ssb/ssb-search2/node_modules/.pnpm/pull-stream@3.6.2/node_modules/pull-stream/sinks/reduce.js:10:5
  at /home/me/prj/ssb/ssb-search2/node_modules/.pnpm/pull-stream@3.6.2/node_modules/pull-stream/sinks/drain.js:20:24
  at /home/me/prj/ssb/ssb-search2/node_modules/.pnpm/pull-stream@3.6.2/node_modules/pull-stream/throughs/filter.js:17:11
  at /home/me/prj/ssb/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/flatten.js:35:20
  at /home/me/prj/ssb/ssb-search2/node_modules/.pnpm/pull-stream@3.7.0/node_modules/pull-stream/throughs/map.js:19:9
```

**Comment by Powersource** [comment]
the first 'generate fixture' test just seems to be a setup thing. if it's run once it doesn't run again. maybe i did: 1. run generate with old ssb-fixtures version 2. update ssb-fixtures with actual breaking changes 3. run stuff with the new ssb-fixtures version but with fixtures from the old version. Now that I've rebooted i lost the old fixtures and got new ones, just like ci
